site_name: OnlyDrops Guide

site_url: https://guide.onlydrops.in

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  show_datetime: false 
  icon: assets/logo.jpg

nav:
  - Welcome to OnlyDrops: index.md
  - Contents: Contents.md

  - Automations:
      - Raffles Tool: automations/saneaio-raffles.md

  - SaneAIO:
      - Overview: saneaio/index.md
      - BMS (Card): saneaio/bm-card.md
      - BMS (Event): saneaio/bm-events.md
      - BMS (UPI): saneaio/bm-upi.md
      - District Queue: saneaio/queue-fair-district-queue.md
      - District Auto: saneaio/queue-fair-district-auto.md
      - Queue-Fair: saneaio/queue-fair.md
      - Myntra: saneaio/myntra.md
      - Superkicks: saneaio/sk.md

  - Utilities:
      - Helper Bot: utilities/helper-bots.md

markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.blocks.details


extra:
  assets:
    exclude: |
      *.zip
      *.mov